version: '3.9'
services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8010:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql-phpmyadmin
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    volumes:
      - ./mysqlData:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dojoplanner
    networks:
      - mysql-phpmyadmin
networks:
  mysql-phpmyadmin:
