### GET request to example server
GET http://localhost:3001/graduacoes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5vbWUiOiJBZG1pbiIsInNvYnJlbm9tZSI6IkxlZ2FuYSIsImVtYWlsIjoiYWRtaW5AbGVnYW5hLmNvbS5iciIsImNsaWVudGVJZCI6ImNtNmtveGUwaDAwMDBnOGs0bXV5NGx2d3QiLCJhY2FkZW1pYUlkIjoiY202cDFuenhvMDAwMWRqZWI3NWgwcWlqNyJ9LCJpYXQiOjE3NDE3OTE4OTMsImV4cCI6MTc0NDM4Mzg5M30.W6NQrAUO1N0pygNx1HLatd0VKSNzbB7SiymKSDUCf6g

### POST request to login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "seu@email.com",
  "password": "suaSenha"
}