export enum CobrancasClienteItemsTipo {
  ALUNO = 'ALUNO',
  PLANO = 'PLANO',
  MODALIDADE = 'MODALIDADE',
  FINANCEIRO = 'FINANCEIRO',
  MENSALIDADE = 'MENSALIDADE',
  PAGAMENTOS = 'PAGAMENTOS',
  CALENDARIO = 'CALENDARIO',
}
